image: alpine/edge
packages:
  - rsync
sources:
  - https://git.sr.ht/~mjorgensen/playground
environment:
  deploy: deploy@playground.jrgnsn.net
secrets:
  - 23f64fde-b028-4f42-83d9-5fd851c76406
triggers:
  - action: email
    condition: always
    to: notify@jrgnsn.net
tasks:
  - deploy:
      rsync  -rP --exclude ".git" playground/ ${deploy}:/var/www/playground/