image: debian/stable
packages:
  - rsync
  - ruby
  - ruby-dev
  - zlib1g-dev
sources:
  - https://git.sr.ht/~mjorgensen/playground
environment:
  deploy: deploy@playground.jrgnsn.net
secrets:
  - 7a042c0a-91f1-4e14-b2cb-5e1aaf23411e
triggers:
  - action: email
    condition: always
    to: notify@jrgnsn.net
tasks:
  - setup: sudo gem install bundler github-pages -N
  - build: |
      cd playground
      bundle install
      bundle exec jekyll build
  - deploy: | 
      cd playground
      sshopts="-o StrictHostKeyChecking=no"
      rsync --rsh="ssh $sshopts" -rP _site/ ${deploy}:/var/www/playground/

