name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        cache-version: 1 # Increment this number if you need to re-download cached gems
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3
    - name: Build the site
      run: |
        make build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        enable_jekyll: true