name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      run: |
        sudo apt install ruby ruby-dev
    - name: Install dependencies
      run: |
        sudo apt install zlib1g-dev
        sudo gem install bundler github-pages -N
    - name: Build the site
      run: |
        make build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        enable_jekyll: true